name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  vita:
    name: Build Vita part
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:20240101

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build bubble
      run: |
        cd bubble
        mkdir build
        cd build
        cmake ..
        make

    - name: Build kernel
      run: |
        cd kernel
        mkdir build
        cd build
        cmake ..
        make

    - name: Build user
      run: |
        cd user
        mkdir build
        cd build
        cmake ..
        make

    - name: Build vsh
      run: |
        cd vsh
        mkdir build
        cd build
        cmake ..
        make

  psp:
    name: Build PSP part
    runs-on: ubuntu-latest
    container: bkcsoft/pspsdk:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build cef
      run: |
        cd cef
        make
